# permissions for end users to view mysqlbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysqlbackup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mysql-operator
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysqlbackup-viewer-role
rules:
- apiGroups:
  - operator.codehorse.com
  resources:
  - mysqlbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.codehorse.com
  resources:
  - mysqlbackups/status
  verbs:
  - get
